---
- name: Include the stunnel mirror variables
  include_vars: stunnel.yml

- name: Make the directory where the stunnel mirrored files will be stored
  file: path={{ stunnel_mirror_location }}
        owner=www-data
        group=www-data
        mode=755
        state=directory

- include: download-and-verify.yml
           project_name="stunnel"
           project_signer="Michal Trojnara"
           project_signing_key="{{ stunnel_michal_trojnara_key_id }}"
           project_expected_fingerprint="{{ stunnel_michal_trojnara_expected_fingerprint }}"
           project_mirror_location="{{ stunnel_mirror_location }}"
           project_download_urls="{{ stunnel_download_urls }}"
