---
- include_vars: tor.yml

- name: Make the directory where the Tor Project's mirrored files will be stored
  file: path={{ tor_mirror_location }}
        owner=www-data
        group=www-data
        mode=755
        state=directory

- name: Erinn Clark signs the Tor Browser Bundles. Import the correct GPG key.
  command: gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys {{ tor_erinn_clark_key_id }}

- name: Register the GPG Key fingerprint output
  command: gpg --fingerprint {{ tor_erinn_clark_key_id }}
  register: tor_erinn_clark_fingerprint

- name: Make sure the retrieved fingerprint perfectly matches the expected fingerprint
  assert: { that: "tor_erinn_clark_expected_fingerprint in tor_erinn_clark_fingerprint.stdout" }

- name: Mirror the Browser Bundles and signatures
  get_url: url={{ item }}
           dest={{ tor_mirror_location }}
  with_items: tor_browser_bundle_urls

- name: Register GPG signature verification results
  shell: for file in *.asc; do gpg --verify $file; done
         chdir={{ tor_mirror_location }}
  register: tor_gpg_verification_results

- name: Make sure the Browser Bundles all passed GPG signature verfication
  assert: { that: "'BAD signature' not in tor_gpg_verification_results.stderr" }
