---
# Set default variables
- include: set-default-variables.yml

- name: Upgrade all installed packages and ensure the APT cache is up to date
  apt: upgrade=yes
       update_cache=yes
       cache_valid_time=3600

- name: Attention, unsupported distribution
  when:  ansible_distribution != 'Debian'
  pause: prompt="Debian 7 is the only fully tested distribution, the setup will probably fail. Press Enter if you still want to continue."

- name: Install Streisand common packages
  apt: name={{ item }}
  with_items: streisand_common_packages

- name: Copy the HTML header and footer templates that are used during documentation generation
  copy: src={{ item.src }}
        dest={{ item.dest }}
  with_items:
    - { src: "header.html", dest: "{{ streisand_header_template }}" }
    - { src: "footer.html", dest: "{{ streisand_footer_template }}" }
