---
# OpenVPN Download variables
# --------------------------
openvpn_mirror_location: "{{ streisand_mirror_location }}/openvpn"
openvpn_mirror_href_base: "/mirror/openvpn"

openvpn_samuli_seppanen_key_id: "0xC29D97ED198D22A3"
openvpn_samuli_seppanen_expected_fingerprint: "0330 0E11 FED1 6F59 715F  9996 C29D 97ED 198D 22A3"

openvpn_version: "2.3.4"
openvpn_base_download_url: "http://swupdate.openvpn.org/community/releases"

openvpn_source_filename: "openvpn-{{ openvpn_version }}.tar.gz"
openvpn_source_sig_filename: "{{ openvpn_source_filename }}.asc"
openvpn_source_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_source_filename }}"
openvpn_source_sig_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_source_sig_filename }}"
openvpn_source_url: "{{ openvpn_base_download_url }}/{{ openvpn_source_filename }}"
openvpn_source_sig_url: "{{ openvpn_base_download_url }}/{{ openvpn_source_sig_filename }}"

openvpn_windows32_installer_filename: "openvpn-install-{{ openvpn_version }}-I002-i686.exe"
openvpn_windows32_installer_sig_filename: "{{ openvpn_windows32_installer_filename }}.asc"
openvpn_windows32_installer_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_windows32_installer_filename }}"
openvpn_windows32_installer_sig_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_windows32_installer_sig_filename }}"
openvpn_windows32_installer_url: "{{ openvpn_base_download_url }}/{{ openvpn_windows32_installer_filename }}"
openvpn_windows32_installer_sig_url: "{{ openvpn_base_download_url }}/{{ openvpn_windows32_installer_sig_filename }}"

openvpn_windows64_installer_filename: "openvpn-install-{{ openvpn_version }}-I002-x86_64.exe"
openvpn_windows64_installer_sig_filename: "{{ openvpn_windows64_installer_filename }}.asc"
openvpn_windows64_installer_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_windows64_installer_filename }}"
openvpn_windows64_installer_sig_href: "{{ openvpn_mirror_href_base }}/{{ openvpn_windows64_installer_sig_filename }}"
openvpn_windows64_installer_url: "{{ openvpn_base_download_url }}/{{ openvpn_windows64_installer_filename }}"
openvpn_windows64_installer_sig_url: "{{ openvpn_base_download_url }}/{{ openvpn_windows64_installer_sig_filename }}"

openvpn_download_urls:
  - "{{ openvpn_source_url }}"
  - "{{ openvpn_source_sig_url }}"
  - "{{ openvpn_windows32_installer_url }}"
  - "{{ openvpn_windows32_installer_sig_url }}"
  - "{{ openvpn_windows64_installer_url }}"
  - "{{ openvpn_windows64_installer_sig_url }}"

# OS X
tunnelblick_version: "3.3.2"
tunnelblick_filename: "Tunnelblick_{{ tunnelblick_version }}.dmg"
tunnelblick_href: "{{ openvpn_mirror_href_base }}/{{ tunnelblick_filename }}"
tunnelblick_url: "http://freefr.dl.sourceforge.net/project/tunnelblick/All%20files/{{ tunnelblick_filename }}"
tunnelblick_checksum: "1e17563771a9536313e68d5a7ff4bddfebcc97a19704ed2a504517b9c7796026"

tunnelblick_beta_version: "3.4beta26"
tunnelblick_beta_filename: "Tunnelblick_{{ tunnelblick_beta_version }}.dmg"
tunnelblick_beta_href: "{{ openvpn_mirror_href_base }}/{{ tunnelblick_beta_filename }}"
tunnelblick_beta_url: "http://freefr.dl.sourceforge.net/project/tunnelblick/All%20files/{{ tunnelblick_beta_filename }}"
tunnelblick_beta_checksum: "fe622f9974f15cc5e3b66f70b1cdc3c3187620219236429809f49c4478a3106e"

tunnelblick_download_urls:
  - { url: "{{ tunnelblick_url }}",      checksum: "{{ tunnelblick_checksum }}" }
  - { url: "{{ tunnelblick_beta_url }}", checksum: "{{ tunnelblick_beta_checksum }}" }
