---
# Shadowsocks Download variables
# ------------------------------
shadowsocks_mirror_location: "{{ streisand_mirror_location }}/shadowsocks"
shadowsocks_mirror_href_base: "/mirror/shadowsocks"

# Windows
shadowsocks_gui_version: "0.4.1"
shadowsocks_gui_filename: "shadowsocks-gui-{{ shadowsocks_gui_version }}-win-ia32.7z"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "http://softlayer-ams.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "b6f5ec6f21bf6a2ff5be75af8d3eb5fe599420b27d81139584c1309c34ade3ee"

# OS X
shadowsocks_x_version: "1.0.9"
shadowsocks_x_filename: "ShadowsocksX-{{ shadowsocks_x_version }}.dmg"
shadowsocks_x_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_x_filename }}"
shadowsocks_x_url: "http://softlayer-ams.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_x_filename }}"
shadowsocks_x_checksum: "b03a430e73c580e47d00bf991680388a87dc03928aaa8f51834394b0819c507b"

# Linux
shadowsocks_python_version: "2.0.9"
shadowsocks_python_filename: "shadowsocks-{{ shadowsocks_python_version }}.tar.gz"
shadowsocks_python_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_python_filename }}"
shadowsocks_python_url: "https://pypi.python.org/packages/source/s/shadowsocks/{{ shadowsocks_python_filename }}"
shadowsocks_python_checksum: "5031e986c8bab02eef32ddc7aab926af8a8fed16fc2ef3947acdb0df70b7d690"

shadowsocks_download_urls:
  - { url: "{{ shadowsocks_gui_url }}",    checksum: "{{ shadowsocks_gui_checksum }}" }
  - { url: "{{ shadowsocks_x_url }}",      checksum: "{{ shadowsocks_x_checksum }}" }
  - { url: "{{ shadowsocks_python_url }}", checksum: "{{ shadowsocks_python_checksum }}" }
