---
- name: Add Tor APT key
  apt_key: id=886DDD89
           data="{{ item }}"
  with_file: tor-signing.key

- name: Add Tor repository
  apt_repository: repo='deb http://deb.torproject.org/torproject.org {{ ansible_lsb.codename }} main'

- name: Install the package to keep the Tor signing key current
  apt: name=deb.torproject.org-keyring
