---
# Provision the Rackspace Server
# ==============================
- hosts: localhost
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "rackspace_region"
      prompt: "What region should the server be located in? Enter 'DFW' for Dallas, 'HKG' for Hong Kong, 'ORD' for Chicago, 'SYD' for Sydney, or 'IAD' for Northern Virginia."
      default: "HKG"
      private: no

    - name: "rackspace_server_name"
      prompt: "What should the server be called? This will be the name of the instance in the Rackspace Control Panel and the server's hostname."
      private: no

    - name: "rackspace_username"
      prompt: "What is your Rackspace username?"
      private: no

    - name: "rackspace_api_key"
      prompt: "What is your Rackspace API key? You can find this in your 'Account Settings' in the Rackspace Control Panel."
      private: no

  roles:
    - genesis-rackspace

- include: streisand.yml
