---
- name: Provision the Rackspace Server
# ====================================
  hosts: localhost
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "rackspace_region"
      prompt: >
        What region should the server be located in?
          DFW = Dallas
          HKG = Hong Kong
          ORD = Chicago
          SYD = Sydney
          IAD = Northern Virginia
      default: "HKG"
      private: no

    - name: "rackspace_server_name"
      prompt: "\nWhat should the server be named?\n"
      private: no

    - name: "rackspace_username"
      prompt: "\nWhat is your Rackspace username?\n"
      private: no

    - name: "rackspace_api_key"
      prompt: "\n\nThe following information can be found in the Rackspace Cloud Control Panel.\nhttps://mycloud.rackspace.com/\n\nWhat is your Rackspace API key?\n"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press any key to continue...\n"

  roles:
    - genesis-rackspace

- include: streisand.yml
