---
- name: Provision the DigitalOcean Server
# =======================================
  hosts: localhost
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "do_region"
      prompt: "Enter the number of the region where the server will be located:\n  1. New York (one)\n  2. Amsterdam (one)\n  3. San Francisco\n  4. New York (two)\n  5. Amsterdam (two)\n  6. Singapore\n  7. London\n"
      default: "5"
      private: no

    - name: "do_server_name"
      prompt: "\nWhat should the server be named?\n"
      default: "streisand"
      private: no

    - name: "do_client_id"
      prompt: "\n\nThe following information can be found on your DigitalOcean control panel.\nhttps://cloud.digitalocean.com/api_access\n\nWhat is your DigitalOcean Client ID?\n"
      private: no

    - name: "do_api_key"
      prompt: "\nWhat is your DigitalOcean API key?\n"
      private: no

  roles:
    - genesis-digitalocean

- include: streisand.yml
