---
- name: Provision the Linode Server
# =================================
  hosts: localhost
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "linode_datacenter"
      prompt: >
        Enter the number of the region where the server will be located:
          2 = Dallas
          3 = Fremont
          4 = Atlanta
          6 = Newark
          7 = London
          8 = Tokyo
      default: "8"
      private: no

    - name: "linode_server_name"
      prompt: "\nWhat should the server be named?\n"
      default: "streisand"
      private: no

    - name: "linode_api_key"
      prompt: "\n\nThe following information can be found in the Linode Manager.\nhttps://manager.linode.com/profile/api\n\nWhat is your Linode API key?\n"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press any key to continue...\n"

  roles:
    - genesis-linode

- include: streisand.yml
