---
# Provision the DigitalOcean Server
# =================================
- hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "do_region"
      prompt: "Region that the server should be located in. '1' for New York 1, '2' for Amsterdam 1, '3' for San Francisco, '4' for New York 2, '5' for Amsterdam 2, and '6' for Singapore."
      default: "5"
      private: no

    - name: "do_server_name"
      prompt: "Server name. This will be the name of the droplet in the DigitalOcean control panel and is also the hostname for the new server."
      private: no

    - name: "do_api_key"
      prompt: "DigitalOcean API key. This can be generated in the API section of the control panel."
      private: no

    - name: "do_client_id"
      prompt: "DigitalOcean Client ID. This can be found in the API section of the control panel."
      private: no

  roles:
    - genesis-digitalocean


# Configure the DigitalOcean Server and install required software
# ===============================================================
- hosts: streisand-host

  user: root

  roles:
    - common
    - openvpn
    - dante
    - stunnel
    - shadowsocks
    - tor-bridge
    - ssh
