---
# Provision the EC2 Server
# ========================
- hosts: localhost
  connection: local
  gather_facts: no

  # These variables are included for the sake of the EC2 Security
  # Group task (which must open various ports)
  vars_files:
    - roles/openvpn/defaults/main.yml
    - roles/shadowsocks/defaults/main.yml
    - roles/ssh/defaults/main.yml
    - roles/stunnel/defaults/main.yml
    - roles/tor-bridge/defaults/main.yml

  vars_prompt:
    - name: "aws_region"
      prompt: "What region should the server be located in? Enter 'ap-northeast-1' for Asia Pacific (Tokyo), 'ap-southeast-1' for Asia Pacific (Singapore), 'ap-southeast-2' for Asia Pacific (Sydney), 'eu-west-1' for EU (Ireland), 'sa-east-1' for South America (Sao Paulo), 'us-east-1' for US East (Northern Virginia), 'us-west-1' for US West (Northern California), or 'us-west-2' for US West (Oregon)."
      default: "ap-southeast-1"
      private: no

    - name: "aws_instance_name"
      prompt: "What should the server be called? This will be the name of the instance in the AWS Management Console and the server's hostname."
      private: no

    - name: "aws_access_key"
      prompt: "What is your AWS Access Key?"
      private: no

    - name: "aws_secret_key"
      prompt: "What is your AWS Secret Key?"
      private: no

  roles:
    - genesis-amazon

# Configure the Server and install required software
# ==================================================
- hosts: streisand-host

  # The standard streisand.yml is not included because the Debian AMI
  # uses 'admin' instead of 'root'
  remote_user: admin
  sudo: yes

  vars:
    # The rc-local role normally expects to configure firewall rules for
    # L2TP/IPsec. Streisand does not install L2TP/IPsec on EC2 servers
    # by default because the instances cannot bind directly to their
    # public IP addresses which makes IPsec routing nearly impossible.
    #
    # This variable is therefore set to an empty value.
    l2tp_ipsec_firewall_rules: ""

  roles:
    - common
    - openvpn
    - dante
    - stunnel
    - shadowsocks
    - ssh
    - tinyproxy
    - tor-bridge
    - streisand-mirror
    - streisand-gateway
