# Configure the Server and install required software
# ===============================================================
- hosts: streisand-host

  remote_user: root

  roles:
    - common
    - streisand-mirror
    - l2tp-ipsec
    - openvpn
    - dante
    - stunnel
    - shadowsocks
    - ssh
    - tinyproxy
    - tor-bridge
