---
- name: Reconfigure SSH to only allow access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config 
              regexp="^#?PasswordAuthentication"
              line="PasswordAuthentication no"
  notify: Restart SSH

- name: Add the SSH forwarding user and generate a key
  user: name=forward
        generate_ssh_key=yes
        ssh_key_comment=streisand
        home={{ forward_location }}
        shell=/usr/sbin/nologin
        comment="SSH Forwarding User"

- name: Register the forwarding user's public SSH key
  command: cat {{ forward_location }}/.ssh/id_rsa.pub
  register: forward_ssh_key

- name: Authorize the key for access
  authorized_key: user=forward
                  key="{{ forward_ssh_key.stdout }}"

- name: Fetch the SSH private key that can be used to connect as the forward user
  fetch: dest={{ streisand_local_directory }}/ssh/
         src={{ forward_location }}/.ssh/id_rsa
         flat=yes
