---
- name: Include the Tor mirror variables
  include_vars: tor.yml

- name: Make the directory where the Tor Project's mirrored files will be stored
  file: path={{ tor_mirror_location }}
        owner=www-data
        group=www-data
        mode=755
        state=directory

- include: download-and-verify.yml
           project_name="Tor Browser Bundle"
           project_signer="Erinn Clark"
           project_signing_key="{{ tor_erinn_clark_key_id }}"
           project_expected_fingerprint="{{ tor_erinn_clark_expected_fingerprint }}"
           project_mirror_location="{{ tor_mirror_location }}"
           project_download_urls="{{ tor_download_urls }}"
