---
- name: Create Azure resource group
  local_action:
    module: azure_rm_resourcegroup
    name: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"
  # for now, we assume to be using  ~/.azure/credentials

# - name: Create the Azure security group
#   local_action:
#     module: azure_rm_securitygroup
#     name: "{{ azure_security_group }}"
#     description: Security group for Streisand
#     resource_group: "{{ azure_resource_group }}"
#     location: "{{ azure_region }}"
#   # for now, we assume to be using  ~/.azure/credentials

# - name: Pause for fifteen seconds to ensure the Azure security group has been created
#   pause:
#     seconds: 15

- name: Open the SSH port in the Azure security group
  local_action:
    module: azure_rm_securitygroup
    name: "{{ azure_security_group }}"
    description: Security group for Streisand
    resource_group: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"
  # for now, we assume to be using  ~/.azure/credentials
    rules:
        destination_port_range: "{{ ssh_port }}"
      # SSH
      # ---
      - name: "AllowSSH"
        destination_port_range: "{{ ssh_port }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 100
  when: open_ssh_port_only

- name: Open all of the necessary ports across every service in the Azure security group
  local_action:
    module: azure_rm_securitygroup
    name: "{{ azure_security_group }}"
    description: Security group for Streisand
    resource_group: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"
  # for now, we assume to be using  ~/.azure/credentials
    rules:
      # Nginx
      # ---
      - name: "AllowNGINX"
        destination_port_range: "{{ nginx_port }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 101
      # OpenConnect (ocserv)
      # ---
      - name: "AllowOCServTCP"
        destination_port_range: "{{ ocserv_port }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 102
      - name: "AllowOCServUDP"
        destination_port_range: "{{ ocserv_port }}"
        protocol: UDP
        access: Allow
        direction: Inbound
        priority: 103
      # OpenVPN
      # ---
      - name: "AllowOpenVPNTCP"
        destination_port_range: "{{ openvpn_port }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 104
      - name: "AllowOpenVPNUDP"
        destination_port_range: "{{ openvpn_port_udp }}"
        protocol: UDP
        access: Allow
        direction: Inbound
        priority: 105
      # Shadowsocks
      # ---
      - name: "AllowShadowsocksTCP"
        destination_port_range: "{{ shadowsocks_server_port }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 106
      # SSH
      # ---
      - name: "AllowSSHTCP"
        destination_port_range: "{{ ssh_port }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 107
      # Stunnel
      # ---
      - name: "AllowStunnelTCP"
        destination_port_range: "{{ stunnel_remote_port }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 108
      # Tor
      # ---
      - name: "AllowTorTCP"
        destination_port_range: "{{ tor_orport }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 109
      # Tor obfs3 port
      # ---
      - name: "AllowOBFS3TCP"
        destination_port_range: "{{ tor_obfs3_port }}"
        protocol: TCP
        access: Allow
        direction: Inbound
        priority: 110
  when: open_all_service_ports
