---
- name: Create Azure resource group
  local_action:
    module: azure_rm_resourcegroup
    name: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"

- name: Create Azure virtual network
  local_action:
    module: azure_rm_virtualnetwork
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_virtual_network }}"
    address_prefixes: "10.10.0.0/16"

- name: Create Azure subnet
  local_action:
    module: azure_rm_subnet
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_subnet }}"
    address_prefix: "10.10.0.0/24"
    virtual_network: "{{ azure_virtual_network }}"

- name: Create Azure public ip
  local_action:
    module: azure_rm_publicipaddress
    resource_group: "{{ azure_resource_group }}"
    allocation_method: Static
    name: "{{ azure_ip }}"

- name: Create Azure security group
  local_action:
    module: azure_rm_securitygroup
    name: "{{ azure_security_group }}"
    resource_group: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"

- name: Open all of the necessary ports across every service in the Azure security group
  local_action:
    module: azure_rm_securitygroup
    name: "{{ azure_security_group }}"
    resource_group: "{{ azure_resource_group }}"
    location: "{{ azure_region }}"
    rules:
      # Nginx
      # ---
      - name: "AllowNGINX"
        destination_port_range: "{{ nginx_port }}"
        protocol: Tcp
        access: Allow
        direction: Inbound
        priority: 101
      # OpenConnect (ocserv)
      # ---
      - name: "AllowOCServTCP"
        destination_port_range: "{{ ocserv_port }}"
        protocol: Tcp
        access: Allow
        direction: Inbound
        priority: 102
      - name: "AllowOCServUDP"
        destination_port_range: "{{ ocserv_port }}"
        protocol: Udp
        access: Allow
        direction: Inbound
        priority: 103
      # OpenVPN
      # ---
      - name: "AllowOpenVPNTCP"
        destination_port_range: "{{ openvpn_port }}"
        protocol: Tcp
        access: Allow
        direction: Inbound
        priority: 104
      - name: "AllowOpenVPNUDP"
        destination_port_range: "{{ openvpn_port_udp }}"
        protocol: Udp
        access: Allow
        direction: Inbound
        priority: 105
      # Shadowsocks
      # ---
      - name: "AllowShadowsocksTCP"
        destination_port_range: "{{ shadowsocks_server_port }}"
        protocol: Tcp
        access: Allow
        direction: Inbound
        priority: 106
      # SSH
      # ---
      - name: "AllowSSHTCP"
        destination_port_range: "{{ ssh_port }}"
        protocol: Tcp
        access: Allow
        direction: Inbound
        priority: 107
      # Stunnel
      # ---
      - name: "AllowStunnelTCP"
        destination_port_range: "{{ stunnel_remote_port }}"
        protocol: Tcp
        access: Allow
        direction: Inbound
        priority: 108
      # Tor
      # ---
      - name: "AllowTorTCP"
        destination_port_range: "{{ tor_orport }}"
        protocol: Tcp
        access: Allow
        direction: Inbound
        priority: 109
      # Tor obfs4 port
      # ---
      - name: "AllowOBFS4TCP"
        destination_port_range: "{{ tor_obfs4_port }}"
        protocol: Tcp
        access: Allow
        direction: Inbound
        priority: 110

- name: Create Azure network interface
  local_action:
    module: azure_rm_networkinterface
    resource_group: "{{ azure_resource_group }}"
    name: "{{ azure_network_interface }}"
    virtual_network: "{{ azure_virtual_network }}"
    subnet: "{{ azure_subnet }}"
    public_ip_name: "{{ azure_ip }}"
    security_group: "{{ azure_security_group }}"
