---
streisand_gateway_url: "https://{{ streisand_ipv4_address }}"

streisand_gateway_htpasswd_file: "/etc/nginx/htpasswd"
streisand_gateway_password_file: "/etc/nginx/gateway-password.txt"

streisand_gateway_markdown_instructions: "/tmp/{{ streisand_server_name }}.md"
streisand_gateway_html_instructions: "/tmp/{{ streisand_server_name }}.html"
