---
streisand_gateway_url: "https://{{ streisand_ipv4_address }}"
streisand_gateway_location: "/var/www/streisand"

streisand_gateway_htpasswd_file: "/etc/nginx/htpasswd"
streisand_gateway_password_file: "/etc/nginx/gateway-password.txt"

streisand_gateway_markdown_instructions: "/tmp/gateway-instructions.md"
streisand_gateway_html_instructions: "/tmp/gateway-instructions.html"

nginx_days_valid: "1825"
nginx_request_subject: "/C={{ nginx_key_country }}/ST={{ nginx_key_province }}/L={{ nginx_key_city }}/O={{ nginx_key_org }}/OU={{ nginx_key_ou }}"

nginx_self_signed_certificate: "/etc/ssl/certs/streisand.crt"
nginx_private_key: "/etc/ssl/private/streisand.key"
