---
- name: Remove the 'streisand' SSH key from DigitalOcean if it already exists. This is to prevent problems if two people with two different keys are sharing the same DigitalOcean account.
  digital_ocean_sshkey: name=streisand
                        state=absent
                        client_id="{{ do_client_id }}"
                        api_key="{{ do_api_key }}"

- name: Get the default SSH key
  command: cat ~/.ssh/id_rsa.pub
  register: ssh_key

- name: Add the SSH key to DigitalOcean
  digital_ocean_sshkey: name=streisand
                        ssh_pub_key="{{ ssh_key.stdout }}"
                        client_id="{{ do_client_id }}"
                        api_key="{{ do_api_key }}"
  register: do_ssh_key

- name: Get the latest 'Debian 7.0 x64' image ID from the DigitalOcean API
  shell: curl -s 'https://api.digitalocean.com/images/?client_id={{ do_client_id }}&api_key={{ do_api_key }}' | python -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [img for img in j["images"] if img["slug"]=="debian-7-0-x64"][0]["id"]'
  register: do_debian7_x64_image_id

- name: Create the server
  digital_ocean: command=droplet
                 name={{ do_server_name }}
                 ssh_key_ids={{ do_ssh_key.ssh_key.id }}
                 client_id="{{ do_client_id }}"
                 api_key="{{ do_api_key }}"
                 size_id={{ do_small_droplet_size_id }}
                 region_id={{ regions[do_region] }}
                 image_id={{ do_debian7_x64_image_id.stdout }}
                 unique_name=yes
  register: streisand_server

- name: Wait until the server has finished booting and OpenSSH is accepting connections
  shell: curl --silent --max-time 5 {{ streisand_server.droplet.ip_address }}:22 | grep 'SSH'
  register: connection_attempt
  until: connection_attempt | success
  retries: 20

- name: Create the in-memory inventory group
  add_host: name={{ streisand_server.droplet.ip_address }}
            groups=streisand-host

- name: Set the streisand_ipv4_address variable
  set_fact: streisand_ipv4_address="{{ streisand_server.droplet.ip_address }}"

- name: Set the streisand_server_name variable
  set_fact: streisand_server_name="{{ do_server_name }}"
