---
# Shadowsocks Download variables
# ------------------------------
shadowsocks_mirror_location: "{{ streisand_mirror_location }}/shadowsocks"
shadowsocks_mirror_href_base: "/mirror/shadowsocks"

# Android
shadowsocks_android_version: "2.6.4"
shadowsocks_android_filename: "shadowsocks-nightly-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_android_filename }}"
shadowsocks_android_url: "https://github.com/shadowsocks/shadowsocks-android/releases/download/v{{ shadowsocks_android_version }}/shadowsocks-nightly-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_checksum: "78e0a3fcd768289a4be877547b0f95523c69539d483083a006e2438713447be9"

# Windows
shadowsocks_gui_version: "0.6.4"
shadowsocks_gui_filename: "shadowsocks-gui-{{ shadowsocks_gui_version }}-win-ia32.tar.xz"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "http://softlayer-ams.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "08896161adffaf3c205f6ac6ec826563aae9dd9a02d33d202d8e910619184e8b"

# OS X
shadowsocks_x_version: "2.5.1"
shadowsocks_x_filename: "ShadowsocksX-{{ shadowsocks_x_version }}.dmg"
shadowsocks_x_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_x_filename }}"
shadowsocks_x_url: "http://softlayer-ams.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_x_filename }}"
shadowsocks_x_checksum: "1f1000ac5b3b7704c377a0c78014628d782014dbf3b3ae60e48c2da8ffc4cccf"

# Linux
shadowsocks_python_version: "2.4.3"
shadowsocks_python_filename: "shadowsocks-{{ shadowsocks_python_version }}.tar.gz"
shadowsocks_python_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_python_filename }}"
shadowsocks_python_url: "https://pypi.python.org/packages/source/s/shadowsocks/{{ shadowsocks_python_filename }}"
shadowsocks_python_checksum: "a38954c7ac3497c6796c1abb96b04bc705bf96039f79ab91fa8dc41607ed74f8"

shadowsocks_download_urls:
  - { url: "{{ shadowsocks_android_url }}", checksum: "{{ shadowsocks_android_checksum }}" }
  - { url: "{{ shadowsocks_gui_url }}",     checksum: "{{ shadowsocks_gui_checksum }}" }
  - { url: "{{ shadowsocks_x_url }}",       checksum: "{{ shadowsocks_x_checksum }}" }
  - { url: "{{ shadowsocks_python_url }}",  checksum: "{{ shadowsocks_python_checksum }}" }
