---
# Shadowsocks Download variables
# ------------------------------
shadowsocks_mirror_location: "{{ streisand_mirror_location }}/shadowsocks"
shadowsocks_mirror_href_base: "/mirror/shadowsocks"

# Android
shadowsocks_android_version: "2.6.5"
shadowsocks_android_filename: "shadowsocks-nightly-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_android_filename }}"
shadowsocks_android_url: "https://github.com/shadowsocks/shadowsocks-android/releases/download/v{{ shadowsocks_android_version }}/shadowsocks-nightly-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_checksum: "16907bcb5c0e51a59fdf6e41c49f0a6265e8dece8b9bb811df98f8d3aaa98233"

# Windows
shadowsocks_gui_version: "2.3.1"
shadowsocks_gui_filename: "Shadowsocks-win-dotnet4.0-{{ shadowsocks_gui_version }}.zip"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "http://iweb.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "d63360b413819f557acab9080718a84c72d5d9768ecccb3e6747408ce05de5a1"

# OS X
shadowsocks_x_version: "2.6.3"
shadowsocks_x_filename: "ShadowsocksX-{{ shadowsocks_x_version }}.dmg"
shadowsocks_x_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_x_filename }}"
shadowsocks_x_url: "http://iweb.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_x_filename }}"
shadowsocks_x_checksum: "f0e263dd1d74b0b6977389f2b8b28c524bceccbc5ad24ca8a8164b92ede1c45a"

# Linux
shadowsocks_python_version: "2.4.3"
shadowsocks_python_filename: "shadowsocks-{{ shadowsocks_python_version }}.tar.gz"
shadowsocks_python_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_python_filename }}"
shadowsocks_python_url: "https://pypi.python.org/packages/source/s/shadowsocks/{{ shadowsocks_python_filename }}"
shadowsocks_python_checksum: "a38954c7ac3497c6796c1abb96b04bc705bf96039f79ab91fa8dc41607ed74f8"

shadowsocks_download_urls:
  - { url: "{{ shadowsocks_android_url }}", checksum: "{{ shadowsocks_android_checksum }}" }
  - { url: "{{ shadowsocks_gui_url }}",     checksum: "{{ shadowsocks_gui_checksum }}" }
  - { url: "{{ shadowsocks_x_url }}",       checksum: "{{ shadowsocks_x_checksum }}" }
  - { url: "{{ shadowsocks_python_url }}",  checksum: "{{ shadowsocks_python_checksum }}" }
