---
# Shadowsocks Download variables
# ------------------------------
shadowsocks_mirror_location: "{{ streisand_mirror_location }}/shadowsocks"
shadowsocks_mirror_href_base: "/mirror/shadowsocks"

# Windows
shadowsocks_gui_version: "0.6.2"
shadowsocks_gui_filename: "shadowsocks-gui-{{ shadowsocks_gui_version }}-win-ia32.tar.xz"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "http://softlayer-ams.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "f04623a6760d6b0376e6941446d5656debbc89ca0093bed6178b5ff3ea4fc05e"

# OS X
shadowsocks_x_version: "2.3"
shadowsocks_x_filename: "ShadowsocksX-{{ shadowsocks_x_version }}.dmg"
shadowsocks_x_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_x_filename }}"
shadowsocks_x_url: "http://softlayer-ams.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_x_filename }}"
shadowsocks_x_checksum: "6aab97a8f5801d20ec779bce6e86349655b27bc6acd8ad70c939b89007be92c5"

# Linux
shadowsocks_python_version: "2.3.2"
shadowsocks_python_filename: "shadowsocks-{{ shadowsocks_python_version }}.tar.gz"
shadowsocks_python_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_python_filename }}"
shadowsocks_python_url: "https://pypi.python.org/packages/source/s/shadowsocks/{{ shadowsocks_python_filename }}"
shadowsocks_python_checksum: "31b3ba74cdd71c0e227fec34a9cfe0304f08fc88a66067381f5f97966fd2c20f"

shadowsocks_download_urls:
  - { url: "{{ shadowsocks_gui_url }}",    checksum: "{{ shadowsocks_gui_checksum }}" }
  - { url: "{{ shadowsocks_x_url }}",      checksum: "{{ shadowsocks_x_checksum }}" }
  - { url: "{{ shadowsocks_python_url }}", checksum: "{{ shadowsocks_python_checksum }}" }
