---
# Shadowsocks Download variables
# ------------------------------
shadowsocks_mirror_location: "{{ streisand_mirror_location }}/shadowsocks"
shadowsocks_mirror_href_base: "/mirror/shadowsocks"

# Windows
shadowsocks_gui_version: "0.6.4"
shadowsocks_gui_filename: "shadowsocks-gui-{{ shadowsocks_gui_version }}-win-ia32.tar.xz"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "http://softlayer-ams.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "08896161adffaf3c205f6ac6ec826563aae9dd9a02d33d202d8e910619184e8b"

# OS X
shadowsocks_x_version: "2.4.1"
shadowsocks_x_filename: "ShadowsocksX-{{ shadowsocks_x_version }}.dmg"
shadowsocks_x_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_x_filename }}"
shadowsocks_x_url: "http://softlayer-ams.dl.sourceforge.net/project/shadowsocksgui/dist/{{ shadowsocks_x_filename }}"
shadowsocks_x_checksum: "9a9c9430420dcaf0fbf68a43c91776fe8f519ce18bccc52f79e3f34819eaa7ea"

# Linux
shadowsocks_python_version: "2.4.3"
shadowsocks_python_filename: "shadowsocks-{{ shadowsocks_python_version }}.tar.gz"
shadowsocks_python_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_python_filename }}"
shadowsocks_python_url: "https://pypi.python.org/packages/source/s/shadowsocks/{{ shadowsocks_python_filename }}"
shadowsocks_python_checksum: "a38954c7ac3497c6796c1abb96b04bc705bf96039f79ab91fa8dc41607ed74f8"

shadowsocks_download_urls:
  - { url: "{{ shadowsocks_gui_url }}",    checksum: "{{ shadowsocks_gui_checksum }}" }
  - { url: "{{ shadowsocks_x_url }}",      checksum: "{{ shadowsocks_x_checksum }}" }
  - { url: "{{ shadowsocks_python_url }}", checksum: "{{ shadowsocks_python_checksum }}" }
