---
# SSH Client Download variables
# -----------------------------
ssh_mirror_location: "{{ streisand_mirror_location }}/ssh"
ssh_mirror_href_base: "/mirror/ssh"

putty_key_id: "0xEEF20295D15F7E8A"
putty_expected_fingerprint: "Key fingerprint = 0A3B 0048 FE49 9B67 A234  FEB6 EEF2 0295 D15F 7E8A"

putty_base_download_url: "http://tartarus.org/~simon/putty-snapshots/x86"

putty_filename: "putty.exe"
putty_sig_filename: "{{ putty_filename }}.gpg"
putty_href: "{{ ssh_mirror_href_base }}/{{ putty_filename }}"
# download-and-verify.yml renames files with non-standard extensions
putty_sig_href: "{{ ssh_mirror_href_base }}/{{ putty_filename }}.asc"
putty_url: "{{ putty_base_download_url }}/{{ putty_filename }}"
putty_sig_url: "{{ putty_base_download_url }}/{{ putty_sig_filename }}"

putty_download_urls:
  - "{{ putty_url }}"
  - "{{ putty_sig_url }}"
