---
# Set default variables
- include: set-default-variables.yml

- name: Upgrade all installed packages and ensure the APT cache is up to date
  apt: upgrade=yes
       update_cache=yes
       cache_valid_time=3600

- name: Install Streisand common packages
  apt: name={{ item }}
  with_items: streisand_common_packages

- name: Create the directory where individual roles will store their Markdown and HTML instructions
  file: path={{ streisand_documentation_directory }}
        owner=root
        group=root
        mode=750
        state=directory

- name: Copy the HTML header and footer templates that are used during documentation generation
  copy: src={{ item[0] }}
        dest={{ item[1] }}
  with_together:
    - [ header.html, footer.html ]
    - [ "{{ streisand_header_template }}", "{{ streisand_footer_template }}" ]

- name: Create the local directory structure for retrieved files and generated documentation
  local_action: >
    file path={{ item }}
         mode=750
         state=directory
  with_items: streisand_local_directory_structure
  sudo: no
