---
# Set default variables
- include: set-default-variables.yml

- name: Upgrade all installed packages and ensure the APT cache is up to date
  apt: upgrade=yes
       update_cache=yes
       cache_valid_time=3600

- name: Install Streisand common packages
  apt: name={{ item }}
  with_items: streisand_common_packages

- name: Create the basic directory structure for retrieved files and generated documentation
  local_action: >
    file path={{ item }}
         mode=750
         state=directory
  with_items: streisand_local_directory_structure
  sudo: no
