---
# Set default variables
- include: set-default-variables.yml

- name: Upgrade all installed packages and ensure the APT cache is up to date
  apt: upgrade=yes
       update_cache=yes
       cache_valid_time=3600

- name: Install Streisand common packages
  apt: name={{ item }}
  with_items: streisand_common_packages

- name: Create the directory where individual roles will store their Markdown and HTML instructions for access via the Gateway
  file: path={{ streisand_gateway_location }}
        owner=www-data
        group=www-data
        mode=750
        state=directory

- name: Copy the HTML header and footer templates that are used during documentation generation
  copy: src={{ item.src }}
        dest={{ item.dest }}
  with_items:
    - { src: "header.html", dest: "{{ streisand_header_template }}" }
    - { src: "footer.html", dest: "{{ streisand_footer_template }}" }
