---
# Set default variables
- include: set-default-variables.yml

- name: Upgrade all installed packages and ensure the APT cache is up to date
  apt: upgrade=yes
       update_cache=yes
       cache_valid_time=3600

- name: Install NTP to make sure the server's clock is set properly
  apt: pkg=ntp

- name: Install the python-software-properties package that the apt_repository module requires
  apt: pkg=python-software-properties

- name: Create the basic directory structure for retrieved files and generated documentation
  local_action: >
    file path={{ item }}
         mode=750
         state=directory
  with_items: streisand_directory_structure
  sudo: no
