---
- name: Upgrade all installed packages and ensure the APT cache is up to date
  apt: upgrade=yes
       update_cache=yes
       cache_valid_time=3600

- name: Install NTP to make sure the server's clock is set properly
  apt: pkg=ntp
