---
- name: Ensure UFW allows SSH
  ufw: to_port="{{ ssh_port }}"
       proto="tcp"
       rule="allow"

- name: Ensure UFW is enabled and denies by default
  ufw: state="enabled"
       policy="deny"
       direction="incoming"

- name: Ensure UFW allows L2TP/IPSec
  ufw: to_port="{{ item }}"
       proto="udp"
       rule="allow"
  with_items:
    - "500"
    - "1701"
    - "4500"
  when: l2tp_ipsec_gateway_location

- name: Ensure UFW allows nginx
  ufw: to_port="{{ nginx_port }}"
       proto="tcp"
       rule="allow"

- name: Ensure UFW allows OpenVPN DNS from 10.8.0.1
  ufw: to_port="53"
       proto="udp"
       rule="allow"
       from_ip="10.8.0.1"

- name: Ensure UFW allows OpenVPN
  ufw: to_port="{{ openvpn_port }}"
       proto="{{ openvpn_protocol | lower }}"
       rule="allow"

- name: Ensure UFW allows Shadowsocks
  ufw: to_port="{{ shadowsocks_server_port }}"
       proto="tcp"
       rule="allow"

- name: Ensure UFW allows stunnel
  ufw: to_port="{{ stunnel_remote_port }}"
       proto="tcp"
       rule="allow"

- name: Ensure UFW allows TOR bridge
  ufw: to_port="{{ tor_orport }}"
       proto="tcp"
       rule="allow"

- name: Ensure UFW allows TOR bfs3 pluggable transport
  ufw: to_port="{{ tor_obfs3_port }}"
       proto="tcp"
       rule="allow"
