---
- name: Provision the DigitalOcean Server
# =======================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1": 2
      "2": 5
      "3": 7
      "4": 1
      "5": 4
      "6": 3
      "7": 6

  vars_prompt:
    - name: "do_region"
      prompt: >
        Enter the number of the region where the server will be located:
          1. Amsterdam (one)
          2. Amsterdam (two)
          3. London
          4. New York (one)
          5. New York (two)
          6. San Francisco
          7. Singapore
      default: "2"
      private: no

    - name: "do_server_name"
      prompt: "\nWhat should the server be named?\n"
      default: "streisand"
      private: no

    - name: "do_client_id"
      prompt: "\n\nThe following information can be found on your DigitalOcean control panel.\nhttps://cloud.digitalocean.com/api_access\n\nWhat is your DigitalOcean Client ID?\n"
      private: no

    - name: "do_api_key"
      prompt: "\nWhat is your DigitalOcean API key?\n"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press Enter to continue...\n"

  roles:
    - genesis-digitalocean

- include: streisand.yml
