---
- name: Provision the DigitalOcean Server
# =======================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1":  "ams2"
      "2":  "ams3"
      "3":  "fra1"
      "4":  "lon1"
      "5":  "nyc1"
      "6":  "nyc2"
      "7":  "nyc3"
      "8":  "sfo1"
      "9":  "sgp1"
      "10": "tor1"

  vars_prompt:
    - name: "do_region"
      prompt: >
        What region should the server be located in?
          1.  Amsterdam        (Datacenter 2)
          2.  Amsterdam        (Datacenter 3)
          3.  Frankfurt
          4.  London
          5.  New York         (Datacenter 1)
          6.  New York         (Datacenter 2)
          7.  New York         (Datacenter 3)
          8.  San Francisco
          9.  Singapore
          10. Toronto
        Please choose the number of your region. Press enter for default (#2) region.
      default: "2"
      private: no

    - name: "do_server_name"
      prompt: "\nWhat should the server be named? Press enter for default (streisand).\n"
      default: "streisand"
      private: no

    - name: "do_access_token"
      prompt: "\n\nNew API access tokens can be generated in the DigitalOcean control panel. When generating a new token, please note that the Write Scope is necessary in order to create Droplets.\nhttps://cloud.digitalocean.com/settings/applications\n\nWhat is your DigitalOcean Access Token?\n"
      private: no

    - name: "do_ssh_name"
      prompt: "\n\nIf you haven't done so already, you must add your SSH public key in the DigitalOcean control panel.\nhttps://cloud.digitalocean.com/settings/security\n\nWhat is the name of the DigitalOcean SSH key that you would like to use?\n"
      default: "streisand"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...\n"

  roles:
    - genesis-digitalocean

- include: streisand.yml
