---
- name: Provision the DigitalOcean Server
# =======================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1": 2
      "2": 5
      "3": 7
      "4": 1
      "5": 4
      "6": 3
      "7": 6

  vars_prompt:
    - name: "do_region"
      prompt: >
        Enter the number of the region where the server will be located:
          1. Amsterdam (one)
          2. Amsterdam (two)
          3. London
          4. New York (one)
          5. New York (two)
          6. San Francisco
          7. Singapore
      default: "2"
      private: no

    - name: "do_server_name"
      prompt: "\nWhat should the server be named?\n"
      default: "streisand"
      private: no

    - name: "do_client_id"
      prompt: "\n\nThe following information can be found on your DigitalOcean control panel.\nhttps://cloud.digitalocean.com/api_access\n\nWhat is your DigitalOcean Client ID?\n"
      private: no

    - name: "do_api_key"
      prompt: "\nWhat is your DigitalOcean API key?\n"
      private: no

    - name: "do_ssh_name"
      prompt: "\n\nThe following information can be found on your DigitalOcean control panel.\nhttps://cloud.digitalocean.com/ssh_keys\n\nWhat is the name of the DigitalOcean SSH key that you would like to use?\n  * If you have never uploaded an SSH key to DigitalOcean then the default\n    value will work!\n  * This key should match your .ssh/id_rsa.pub file.\n\  * DigitalOcean requires SSH keys to be unique. You cannot upload multiple\n    keys that have the same value under different names.\n\n    If you see an error that says 'SSH Key failed to be created' once the setup\n    process starts, then this is the problem. You can retry the setup process\n    using the name of the existing SSH key that matches the contents of your\n    RSA public key.\n"
      default: "streisand"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press Enter to continue...\n"

  roles:
    - genesis-digitalocean

- include: streisand.yml
