---
- name: Provision the Linode Server
# =================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    regions:
      "1": 4
      "2": 2
      "3": 3
      "4": 7
      "5": 6
      "6": 8

  vars_prompt:
    - name: "linode_datacenter"
      prompt: >
        Enter the number of the region where the server will be located:
          1. Atlanta
          2. Dallas
          3. Fremont
          4. London
          5. Newark
          6. Tokyo
      default: "6"
      private: no

    - name: "linode_server_name"
      prompt: "\nWhat should the server be named?\n"
      default: "streisand"
      private: no

    - name: "linode_api_key"
      prompt: "\n\nThe following information can be found in the Linode Manager.\nhttps://manager.linode.com/profile/api\n\nWhat is your Linode API key?\n"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press Enter to continue...\n"

  roles:
    - genesis-linode

- include: streisand.yml
