- name: Configure the Server and install required software
# ========================================================
  hosts: streisand-host

  remote_user: root

  roles:
    - common
    - l2tp-ipsec
    - openconnect
    - openvpn
    - stunnel
    - shadowsocks
    - ssh
    - tinyproxy
    - tor-bridge
    - sslh
    - monit
    - ufw
    - streisand-mirror
    - streisand-gateway
