---
openvpn_days_valid: "1825"
openvpn_request_subject: "/C={{ openvpn_key_country }}/ST={{ openvpn_key_province }}/L={{ openvpn_key_city }}/O={{ openvpn_key_org }}/OU={{ openvpn_key_ou }}"
openvpn_key_size: "2048"
openvpn_cipher: "AES-256-CBC"
openvpn_auth_digest: "SHA256"
openvpn_path: "/etc/openvpn"
openvpn_ca: "{{ openvpn_path }}/ca"
openvpn_dhparam: "{{ openvpn_path }}/dh{{ openvpn_key_size }}.pem"
openvpn_hmac_firewall: "{{ openvpn_path }}/ta.key"
openvpn_server: "{{ ansible_default_ipv4.address }}"

openvpn_direct_profile_filename: "{{ openvpn_server }}-direct.ovpn"
openvpn_stunnel_profile_filename: "{{ openvpn_server }}-stunnel.ovpn"

openvpn_firewall_rules:
  - iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
  - iptables -A FORWARD -s 10.8.0.0/24 -j ACCEPT
  - iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o {{ ansible_default_ipv4.interface }} -j MASQUERADE
